#!/bin/zsh

function handle_file {
    while read line; do
        notmuch-lazysync record -v -- notmuch tag $remove $line
    done <$1
}

notmuch_bin=""
which -a notmuch | while read bin; do
    if [[ "$bin" != "$0" ]]; then
       notmuch_bin="$bin"
       break
    fi
done

if [[ -z $notmuch_bin ]]; then
    echo "No notmuch binary found" >&2
    exit 1
fi

if [[ "$1" == "tag" ]]; then
    # note that comm truncates the name after 15 characters
    if [[ $(ps -p $PPID -o comm=) != "notmuch-lazysyn" ]]; then
        input=""
        batch=0
        remove=""
        for arg in "$@"; do
            if [[ "$arg" == "--batch" ]]; then
                batch=1
            elif [[ "$arg" =~ '^--input=(.*)$' ]]; then
                input=$match[1]
            elif [[ "$arg" == "--remove-all" ]]; then
                 remove="--remove-all"
            elif [[ "$arg" == "--" ]]; then
                break
            fi
        done
        if [[ $input != "" && -f $input ]]; then
            handle_file "$input"
            $notmuch_bin "$@"
        elif [[ $batch -ne 0 ]]; then
            tmpfile=`mktemp`
            tee $tmpfile | $notmuch_bin "$@"
            retval=$?
            handle_file "$tmpfile"
            rm $tmpfile
            exit $retval
        else
            notmuch-lazysync record -v -- notmuch "$@" &
            $notmuch_bin "$@"
        fi
    else
        $notmuch_bin "$@"
    fi
else
    $notmuch_bin "$@"
fi
